/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package encodedecode;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */

public class Register extends javax.swing.JFrame {
    
    JFrame f;

    private JFrame frame;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CPasstxt = new javax.swing.JTextField();
        Passtxt = new javax.swing.JTextField();
        Nametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(CPasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, 37));
        jPanel2.add(Passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, 37));
        jPanel2.add(Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 260, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Comfirm Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 135, 64));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Pass = Passtxt.getText();
        String CPass = CPasstxt.getText();
        String name = Nametxt.getText();
        String path;
        String Regis = Pass;
        if(Pass.equals(CPass)){
            
      
            try {
                
                
                BufferedReader Read = new BufferedReader(new FileReader("C:\\Users\\Hp\\OneDrive\\Desktop\\project_User_storage\\UserInfor\\"+name+".txt"));
                if(Read.readLine().equals(null)){             
                            try {
                                FileWriter Register = new FileWriter("C:\\Users\\Hp\\OneDrive\\Desktop\\project_User_storage\\UserInfor\\"+name+".txt");                    
                                Register.write(Regis);
                                Register.close();
                                
                               

                                } catch (IOException ex) {
                                   
                                }  	                
                        }else{                  
                                frame = new JFrame("Exit");
                                JOptionPane.showMessageDialog(frame,"This name is not available.","Alert",JOptionPane.WARNING_MESSAGE);                                      
                        }   
            Read.close();
   
            } catch (FileNotFoundException ex) {
                
                try {
                    path = "C:\\Users\\Hp\\OneDrive\\Desktop\\project_User_storage\\"+name;
                    File f1 = new File(path);
                    boolean bool = f1.mkdir();  
                    if(bool){  
                        System.out.println("Folder is created successfully");  
                    }else{  
                        System.out.println("Error Found!");  
                    }  
                    File myObj = new File("C:\\Users\\Hp\\OneDrive\\Desktop\\project_User_storage\\UserInfor\\"+name+".txt");
                    FileWriter Register = new FileWriter("C:\\Users\\Hp\\OneDrive\\Desktop\\project_User_storage\\UserInfor\\"+name+".txt");
                    Register.write(Regis);
                    
                    frame = new JFrame("Exit");
                    JOptionPane.showMessageDialog(frame,"Success !.","Alert",JOptionPane.WARNING_MESSAGE);
                    Register.close();
                } catch (IOException ex1) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex1);
                }
                
            } catch (IOException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                        
        }else{
        
        JOptionPane.showMessageDialog(f, "Password incorrent.","Warning !",JOptionPane.PLAIN_MESSAGE);
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPasstxt;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField Passtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
