/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myclass.testdb;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUN_KaveewatPC
 */
public class CART extends javax.swing.JFrame {

    /**
     * Creates new form CART
     */
    public CART() {
        initComponents();
    }
    
    public void calTable(){
    
        int numrow = jTable1.getRowCount();
        
        double tot = 0 ;
        
        for(int i = 0 ; i < numrow ; i++){
            double val = Double.valueOf(jTable1.getValueAt(i , 3).toString());
            double val1 = Double.valueOf(jTable1.getValueAt(i , 2).toString());
            tot += val1 * val;

        }
        
    jLabel3.setText("PRICE : " + tot);

    }
private String UserID = "";
    public void getIDUser(){
        try {
            DbConnector db = new DbConnector();
            ResultSet rs = db.Getresultset("select * from `customer`");
            while (rs.next()) {
                
                String myUser = rs.getString(2);

                if (usename1.equalsIgnoreCase(myUser)) {
                    UserID = rs.getString(1);
                                              
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();

        }
    
    }
    

private String usename1 ;
private ArrayList<String> lists1 = new ArrayList<>(); 
private ArrayList<String> lists2 = new ArrayList<>(); 
private ArrayList<String> lists3 = new ArrayList<>(); 
private ArrayList<String> lists4 = new ArrayList<>(); 
    CART(ArrayList<String> list1, ArrayList<String> list2, String Username) {
        initComponents();
        DT();
        jLabel1.setText("TIME : " + date1);
        lists1 = list1;
        lists2 = list2;
        
        usename1 = Username;
        jLabel2.setText("NAME : "+usename1);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        String[] itemsArray1 = new String[lists1.size()];
        itemsArray1 = lists1.toArray(itemsArray1);
        String[] itemsArray2 = new String[lists2.size()];
        itemsArray2 = lists2.toArray(itemsArray2);

        for(String s : itemsArray1)
            System.out.println("itemsArray2 = " +s);
        
        try {
                  
            for(int i = 0 ; i < itemsArray1.length ; i ++){
                
                DbConnector db = new DbConnector();
                ResultSet rs = db.Getresultset("select * from `product`");
                while (rs.next()) {

                    String myUser = rs.getString(1);

                    if (itemsArray1[i].equalsIgnoreCase(myUser)) {
                        System.out.println("Array1 = " + i + " price = " + rs.getString(5));
                        lists3.add(rs.getString(5));
                        lists4.add(rs.getString(2));
                       
                                                  
                    }
                }
            }
            
        String[] itemsArray3 = new String[lists3.size()];
        itemsArray3 = lists3.toArray(itemsArray3);
        String[] itemsArray4 = new String[lists4.size()];
        itemsArray4 = lists4.toArray(itemsArray4);
            
        for(String s : itemsArray1)
            System.out.println("itemsArray1 = " +s);
        for(String s : itemsArray2)
            System.out.println("itemsArray2 = " +s);
        for(String s : itemsArray3)
            System.out.println("itemsArray3 = " +s);
        
        
        for(int i = 0 ; i < itemsArray1.length ; i ++ ) {
        
            model.insertRow(model.getRowCount(),new Object[]{itemsArray1[i],itemsArray4[i],itemsArray2[i],itemsArray3[i]}); 
        }  
        } catch (SQLException ex) {
            ex.printStackTrace();       
        }       
        calTable();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QTY", "PRICE/1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("PRICE :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 160, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("PAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 170, 40));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 60, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("TIME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        

        setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        if(jTable1.getSelectedRowCount() == 1){
            model.removeRow(jTable1.getSelectedRow());
        }
        calTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed
private String date1;
    public void DT(){
    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");       
       LocalDateTime now = LocalDateTime.now();
       date1 = dtf.format(now);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        getIDUser();
         try {
        int r = 0;
        String sql1 = ("SELECT * FROM `order`");
        DbConnector Connec = new DbConnector();
        
        ResultSet rs = Connec.Getresultset(sql1);
        
        while(rs.next()){
            r = rs.getInt(1);
            }
        System.out.println("R = " + r);
        r++;
        
        
        int numrow = jTable1.getRowCount();
        DbConnector CON0123 = new DbConnector();
        
        for(int i = 0 ; i < numrow ; i++){
        String Price = (jTable1.getValueAt(i , 3).toString());
        String QTY = (jTable1.getValueAt(i , 2).toString());
        String Itemname = (jTable1.getValueAt(i , 1).toString());
        String ItemId = "";
        String sql3 = ("SELECT * FROM `product`");
        ResultSet rs3 = Connec.Getresultset(sql3);
        
        while(rs3.next()){
            
                String itna = rs3.getString(2);
                if(Itemname.equals(itna)){
                        ItemId = rs3.getString(1);

                        String SQL = String.format("INSERT INTO `order`(OrderID,CustomerID,PruductID,Quantity,Date_,PricePerOne) VALUES('%s','%s','%s','%s','%s','%s')", r , (UserID) ,  (ItemId)  , (QTY), date1 , (Price) );
                        CON0123.Execute(SQL);
        
                    }
                
                
        
        }
        
            String amount = "0";     
                String sql4 = ("SELECT * FROM product");
                ResultSet rs4 = Connec.Getresultset(sql4);               
                
                while(rs4.next()){
                    String ItemNames = rs4.getString(1);
                    if(ItemId.equals(ItemNames)){
                        amount = rs4.getString(7);

                    }
                }
                int sum = Integer.parseInt(amount) - Integer.parseInt(QTY);


                String SQL1 = String.format("UPDATE product SET QTY = '%s' WHERE Product_ID = '%s' " , sum , ItemId);
                CON0123.Execute(SQL1);
                JOptionPane.showMessageDialog(null, "Complete !");
                setVisible(false);

        }
        
        
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CART.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CART().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
